name: Daily Portal Watchdog

on:
  schedule:
    # Runs every day at 9:00 AM IST (03:30 UTC)
    - cron: '30 3 * * *'
  workflow_dispatch:  # lets you trigger manually if needed

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pyppeteer

      - name: Run watchdog
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python watchdog_full_digest_split.py
